version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: sanfootball/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/media
    depends_on:
      - db
  frontend:
    image: sanfootball/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
    depends_on:
      - backend
  gateway:
    image: sanfootball/foodgram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/staticfiles
      - media:/media