# Generated by Django 3.2.19 on 2023-08-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=10, unique=True, verbose_name='Цвет тега'),
        ),
    ]
