# Generated by Django 3.2.19 on 2023-08-18 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230812_1335'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
